### ISSUE TITLE
Extracting amino acid sequences from extractSeqFromGBK.py?

### ISSUE THREAD

**Issue by mhyleung** [wanyuac/BINF_toolkit#11]
Dear all

Thank you for developing this neat tool suite. I was wondering if the extractSeqFromGBK.py script can also extract sequences, if the CDS sections of my .gbk file contains the translated amino acid sequences.

Thank you!

Regards

Marcus

**Comment by wanyuac** [comment]
Hi Marcus,

You can extract amino acid sequences from GenBank files by adding the flag `-a` or `--aa` when using `extractSeqFromGBK.py`. Example:
```python extractSeqFromGBK.py --targets genes.tsv --gbk *.gbk --usegene --aa --extname > proteins.faa```
